import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/dashboard/layout'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dashboard - Gestion de votre portefeuille en ligne</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="index.css" />
      </Head>
      <Layout>
        <h1>Dashboard</h1>
      </Layout>
    </div>
  )
}

export default Home