import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/default/layout'

import { AiOutlineShoppingCart } from 'react-icons/ai'
import { FiPercent } from 'react-icons/fi'
import { BsCashCoin } from 'react-icons/bs'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Application de cashback - Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="index.css" />
      </Head>
      <Layout navigation>
        <div className="relative h-2/4 pt-8 px-4 flex flex-col md:flex-row items-center z-10">
          <div className="w-full md:w-2/4">
            <h1 className="text-2xl font-semibold text-black sm:text-3xl md:text-3xl">
                <span className="block leading-snug xl:inline">Soon vous reverse de l'argent lorsque vous achetez sur internet, c'est le</span>{' '}
                <span className="block leading-snug text-blue xl:inline">cashback !</span>
            </h1>
            <button className="mt-10 bg-blue-dark rounded px-8 py-4 flex font-semibold items-center justify-center text-xl text-white">Je m’inscris gratuitement - 3€ offerts</button>
          </div>
          <div className="w-full md:w-2/4">
            <img className="w-full mx-auto" src="./images/hero.png" />
          </div>
        </div>
        <div className="hero_banner absolute top-10 md:top-16 bg-pink w-full h-full md:h-2/4 opacity-20 z-0" />

        <div className="mt-12 z-20 w-full text-center">
          <h2 className="font-bold text-xl md:text-2xl mb-16">Comment fonctionne le cashback ?</h2>
          <div className="flex flex-wrap justify-center md:justify-between">
            <div className="mb-16 flex flex-col items-center justify-center w-screen max-w-xs px-8">
              <AiOutlineShoppingCart className="text-6xl text-pink" />
              <span className="text-white mb-4 rounded-full w-8 h-8 bg-pink flex items-center justify-center font-bold text-xs ring-4 ring-pink ring-opacity-50 mt-8">01</span>
              <p>Je fais mes achats en passant par iGraal</p>
            </div>
            <div className="mb-16 flex flex-col items-center justify-center w-screen max-w-xs px-8">
              <FiPercent className="text-6xl text-pink" />
              <span className="text-white mb-4 rounded-full w-8 h-8 bg-pink flex items-center justify-center font-bold text-xs ring-4 ring-pink ring-opacity-50 mt-8">01</span>
              <p>On me rembourse une partie du montant de mon achat</p>
            </div>
            <div className="mb-16 flex flex-col items-center justify-center w-screen max-w-xs px-8">
              <BsCashCoin className="text-6xl text-pink" />
              <span className="text-white mb-4 rounded-full w-8 h-8 bg-pink flex items-center justify-center font-bold text-xs ring-4 ring-pink ring-opacity-50 mt-8">01</span>
              <p>Je récupère mes gains sur mon compte bancaire</p>
            </div>
          </div>
          <div className="bg-black bg-opacity-50 p-5 rounded">
            <h2 className="font-bold text-xl text-left pl-8">Inscrivez vous à notre newsletter</h2>
            <form action="" className="py-8 flex flex-col items-center justify-center">
              <input className="my-2 px-4 py-2 rounded w-full max-w-md" type="text" placeholder="Votre prenom" />
              <input className="my-2 px-4 py-2 rounded w-full max-w-md" type="text" placeholder="Votre email" />
              <input className="my-2 px-4 py-2 rounded w-full max-w-md" type="submit" />
            </form>
          </div>
          <footer className="text-center py-2 border-t md:border-none">Powered by Hugo</footer>
        </div>
      </Layout>
    </div>
  )
}

export default Home
